# SPDX-License-Identifier: AGPL-3.0-or-later

- type: latheRecipe
  abstract: true
  id: BaseRedAlert
  requiredAlerts:
  - Red
  - Gamma
  - DeltaBlob
  - DeltaDelam
  - DeltaNuke
  - DeltaSling
  - Omicron
  - Octarine
  # inky start - kill chud lock
  - Green
  - Blue
  # inky end

- type: latheRecipe
  abstract: true
  id: BaseBlueAlert
  requiredAlerts:
  - Blue
  - Red
  - Gamma
  - DeltaBlob
  - DeltaDelam
  - DeltaNuke
  - DeltaSling
  - Omicron
  - Octarine
  # inky start - kill chud lock
  - Green
  # inky end
