# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antagSpecifier
  id: LoneXenomorph
  spawnerPrototype: SpawnPointGhostLoneXenomorph
  allowNonHumans: true
  mindRoles: [ MindRoleLoneXenomorph ]
  briefing:
    text: lone-xenomorph-role-greeting
    color: "#8c3986"

- type: antag
  id: LoneXenomorph
  name: ghost-role-information-lone-xenomorph-name
  objective: ghost-role-information-lone-xenomorph-description
  antagonist: true
