# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antagSpecifier
  id: LoneXenomorph
  spawnerPrototype: SpawnPointGhostLoneXenomorph
  allowNonHumans: true
  mindRoles: [ MindRoleLoneXenomorph ]
  briefing:
    # SIS-ChatGreeting Start
    # text: lone-xenomorph-role-greeting
    # color: "#8c3986"
    theme:
      titleBackground: "#190e1c"
      titleBorder: "#8c3986"
      messageBackground: "#0d070f"
      messageBorder: "#331538"
      titleText: "#d680d0"
      messageText: "#e4d4e6"
      titleHighlight1: "#8c3986"
      messageHighlight1: "#8c3986"
      messageHighlight2: "#e4d4e6"
    sections:
    - title: role-greeting-title
      message: lone-xenomorph-role-greeting
    - title: role-greeting-desc
      message: lone-xenomorph-role-greeting-desc
    # SIS-ChatGreeting End

- type: antag
  id: LoneXenomorph
  name: ghost-role-information-lone-xenomorph-name
  objective: ghost-role-information-lone-xenomorph-description
  antagonist: true
