# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Spy
  name: roles-antag-spy-name
  objective: roles-antag-spy-objective
  antagonist: true
  setPreference: true
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h
  guides: [ Spy ]

- type: antagSpecifier
  parent: RestrictedAntag
  id: Spy
  # SIS-ChatGreeting Start
  briefing:
    sound: /Audio/_Trauma/Ambience/Antag/spy.ogg
    theme:
      titleBackground: "#0a1410"
      titleBorder: "#2f9e44"
      messageBackground: "#060d0a"
      messageBorder: "#1b3a24"
      titleText: "#8ce99a"
      messageText: "#d3f9d8"
      titleHighlight1: "#2f9e44"
      messageHighlight1: "#2f9e44"
      messageHighlight2: "#b2f2bb"
  # SIS-ChatGreeting End
  prefRoles:
  - Spy
  mindRoles:
  - MindRoleSpy

- type: antagSmite
  id: Spy
  antag: Spy
  rule: Spies
  ruleComp: SpyRule
  icon:
    sprite: _ShitChap/Objects/Weapons/Nullrod/atheist.rsi
    state: icon
